config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, path: "auth", skip: [:registrations]

  as :user do
    get "change_password/edit" => "devise/registrations#edit", as: "edit_user_registration"
    patch "change_password" => "devise/registrations#update", as: "user_registration"
  end

  resources :users do
    get "reinvite", on: :member
  end

  resources :regimes, only: [] do
    resources :permit_categories  # , only: [:index]
    resources :permit_categories_lookup, only: [:index]
    resources :transactions, only: %i[index show edit update] do
      put "approve", on: :collection
      get "audit", on: :member
    end
    resources :history, only: %i[index show]
    resources :retrospectives, only: %i[index show]
    resources :exclusions, only: [:index]
    resources :transaction_files, only: %i[index create]
    resources :imported_transaction_files, only: %i[index show edit update]
    resources :transaction_summary, only: %i[index show]
    resources :retrospective_files, only: [:create]
    resources :retrospective_summary, only: [:index]
    resources :annual_billing_data_files, except: [:destroy]
    resources :exclusion_reasons, except: [:show]
    resources :data_export, only: [:index] do
      get "download", on: :collection
      get "generate", on: :collection
    end
  end

  root to: "transactions#index"

  require "resque/server"
  authenticate(:user, ->(u) { u.admin? }) do
    mount Resque::Server, at: "/jobs"
  end

  match "/404", to: "errors#not_found", via: :all
  match "/422", to: "errors#unprocessable_entity", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  enum role: %i[billing admin read_only read_only_export]
  enum active_regime: %i[cfd pas wml]

  has_many :regime_users, inverse_of: :user, dependent: :destroy
  has_many :regimes, -> { merge(RegimeUser.enabled) }, through: :regime_users
  has_many :audit_logs, inverse_of: :user
  has_many :transaction_files, inverse_of: :user
  has_many :approved_transactions, class_name: "TransactionDetail", foreign_key: :approver_id, inverse_of: :approver
  has_many(
    :removed_transaction_files,
    class_name: "TransactionHeader",
    foreign_key: :removed_by_id,
    inverse_of: :removed_by
  )
  after_save :ensure_a_default_regime_is_set

  accepts_nested_attributes_for :regime_users

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :recoverable, :rememberable,
         :trackable, :lockable, :timeoutable, :registerable, :validatable

  validates :email, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validate :at_least_one_regime_selected
  validate :password_complexity

  def self.system_account
    find_by!(email: "system@example.com")
  end

  def self.ordered_roles
    %i[read_only read_only_export billing admin]
  end

  def self.search(str)
    m = "%#{sanitize_sql_like(str)}%"
    where(arel_table[:first_name].matches(m).or(arel_table[:last_name].matches(m)))
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def can_reinvite?
    persisted? && enabled? && invitation_accepted_at.nil?
  end

  def active_for_authentication?
    enabled?
  end

  def selected_regime
    if active_regime.nil?
      set_default_regime
    else
      regimes.find_by(slug: active_regime)
    end
  end

  def apply_regime(regime_id)
    reg = regimes.find_by(slug: regime_id)
    if reg
      send("#{reg.to_param}!") unless active_regime == reg.to_param
      reg
    else
      set_default_regime
    end
  end

  def can_read_only?
    read_only? || read_only_export?
  end

  def can_export_data?
    admin? || billing? || read_only_export?
  end

  private

  def set_default_regime
    reg = regimes.order(:title).first
    send("#{reg.to_param}!")
    reg
  end

  def at_least_one_regime_selected
    selected = regime_users.select(&:enabled?).count
    errors.add :regime, "^Access to at least one Regime is required" if selected.zero?
  end

  def ensure_a_default_regime_is_set
    set_default_regime unless regimes.map(&:slug).include? active_regime
  end

  def password_complexity
    return unless password.present?
    return if password.match(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)/)

    errors.add :password, "does not meet complexity requirements"
  end
end

app/models/view_models/users.rb
# frozen_string_literal: true

module ViewModels
  class Users
    include ActionView::Helpers::FormOptionsHelper
    include RegimeScope

    attr_accessor :regime, :role, :search, :sort,
                  :sort_direction, :page, :per_page

    def initialize(params = {})
      @regime = params.fetch(:regime, "")
      @search = ""
      @role = ""
      @page = 1
      @per_page = 10
      @sort = "last_name"
      @sort_direction = "asc"
    end

    def users
      @users ||= fetch_check_users
    end

    def paged_users
      @paged_users ||= users.page(page).per(per_page)
    end

    def check_params
      @regime = "" if regime == "all"
      @role = "" if role == "all"
      @page = 1 if page.blank?
      @page = 1 unless page.to_i.positive?
      @per_page = 10 if per_page.blank?
      @per_page = 10 unless per_page.to_i.positive?
      # fetch transactions to validate/reset page
      users
    end

    def fetch_check_users
      t = fetch_users
      pg = page.to_i
      perp = per_page.to_i
      max_pages = (t.count / perp.to_f).ceil
      @page = 1 if pg > max_pages
      t
    end

    # override me for different views
    def fetch_users
      Query::Users.call(regime: regime,
                        role: role,
                        sort: sort,
                        sort_direction: sort_direction,
                        search: search)
    end

    def regime_options
      options_for_select([["All", ""]] +
                         available_regimes.map { |r| [r.title, r.slug] },
                         regime)
    end

    def role_options
      options_for_select([["All", ""]] +
                         available_roles.map { |r| [r[:name], r[:value]] },
                         role)
    end

    private

    def available_regimes
      @available_regimes ||= Regime.all.order(:title)
    end

    def available_roles
      @available_roles ||= User.ordered_roles.map do |r|
        { name: I18n.t(r, scope: "user.roles"), value: User.roles[r] }
      end
    end

    def page_and_present_transactions
      pt = paged_transactions
      Kaminari.paginate_array(presenter.wrap(pt, user),
                              total_count: pt.total_count,
                              limit: pt.limit_value,
                              offset: pt.offset_value)
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < AdminController
  include ViewModelBuilder
  before_action :set_user, only: %i[show edit update reinvite]

  def index
    @view_model = build_users_view_model
    respond_to do |format|
      format.html do
        render partial: "table", locals: { view_model: @view_model } if request.xhr?
      end
    end
  end

  def show; end

  def new
    # default to role with lowest rights
    @user = User.new(role: "read_only")
    build_regimes
  end

  def create
    p = user_params.merge(password: "#{Devise.friendly_token.first(8)}Az9")
    @user = User.create(p)

    if @user.valid?
      invite_user(@user)
      redirect_to users_path, notice: "User account created"
    else
      render :new
    end
  end

  def edit
    build_regimes
  end

  def update
    if @user.update(user_params.except(:email))
      redirect_to users_path, notice: "User account updated"
    else
      render :edit
    end
  end

  def reinvite
    invite_user(@user)
    redirect_to edit_user_path(@user), notice: "User reinvited"
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :first_name, :last_name, :password,
                                 :enabled, :role,
                                 regime_users_attributes: %i[id regime_id enabled])
  end

  def build_regimes
    Regime.order(:title).each do |regime|
      @user.regime_users.find_or_initialize_by(regime_id: regime.id)
    end
  end

  def invite_user(user)
    user.invite!(current_user) do |u|
      u.skip_invitation = true
    end
    # invitation token not persisted (or serialized?) so need to grab it now
    invitation_link = accept_user_invitation_url(
      invitation_token: user.raw_invitation_token
    )
    UserMailer.invitation(user.email, user.full_name, invitation_link).deliver_later
    user.update(invitation_sent_at: Time.now.utc)
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  def user_submit_button(form)
    title = form.object.new_record? ? "Add and Invite User" : "Update User"
    form.submit(title, class: "btn btn-primary")
  end

  def role_label(name)
    t(name.to_s, scope: "user.roles")
  end

  def regime_names(user)
    user.regimes.map(&:title).join(", ")
  end
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true ) do |form| %>
  <%= error_header(user) %>

  <fieldset class="mt-4">
    <legend>User details</legend>
    <div class="row">
      <%= error_group(user, :email, class: "col-lg-6") do %>
        <div class="form-group">
          <%= form.label :email %>
          <%= form.text_field :email, id: :user_email,
            class: "form-control", readonly: user.persisted? %>
        </div>
      <% end %>
    </div>
    <div class="row">
      <%= error_group(user, :first_name, class: "col-lg-6") do %>
        <div class="form-group">
          <%= form.label :first_name %>
          <%= form.text_field :first_name, id: :user_first_name,
            class: "form-control" %>
        </div>
      <% end %>
    </div>
    <div class="row">
      <%= error_group(user, :last_name, class: "col-lg-6") do %>
        <div class="form-group">
          <%= form.label :last_name %>
          <%= form.text_field :last_name, id: :user_last_name,  class: "form-control" %>
        </div>
      <% end %>
    </div>
    <div class="row ml-2">
      <div class="col-lg-6">
        <div class="form-check">
          <%= form.check_box :enabled, id: :user_enabled, class: "form-check-input" %>
          <%= form.label :enabled, class: 'form-check-label' %>
        </div>
      </div>
    </div>
  </fieldset>
  <div class="row">
    <fieldset class="col-lg-3 col-sm-6 mt-4">
      <legend>Role</legend>
      <div class="row ml-2">
        <div class="col">
          <%# @user.defined_enums['role'].each do |k, _| %>
          <% User.ordered_roles.each do |r| %>
            <div class="form-check">
              <%= form.radio_button :role, r, id: "role_#{r}", class: "form-check-input" %>
              <%= form.label :role, role_label(r), for: "role_#{r}", class: 'form-check-label' %>
            </div>
          <% end %>
        </div>
      </div>
    </fieldset>
    <%= error_group(user, :regime, class: "col-lg-3 col-sm-6 mt-4") do %>
      <fieldset>
        <legend>Regime Access</legend>
        <%= form.fields_for :regime_users do |ff| %>
          <%= ff.hidden_field :regime_id %>
          <div class="row ml-2">
            <div class="col">
              <div class="form-check">
                <%= ff.check_box :enabled, class: "form-check-input" %>
                <%= ff.label :enabled, ff.object.regime.title, class: 'form-check-label' %>
              </div>
            </div>
          </div>
        <% end %>
      </fieldset>
    <% end %>
  </div>
  <div class="row mt-4 mb-4">
    <div class="col-lg-6 actions">
      <%= user_submit_button(form) %>
      <% if user.can_reinvite? %>
        <%= link_to 'Resend Invitation', reinvite_user_path(user),
          class: 'btn btn-warning mr-4', role: 'button' %>
      <% end %>
      <%= link_to 'Cancel', users_path, class: 'btn btn-secondary', role: 'button' %>
    </div>
  </div>
<% end %>

app/views/users/_pagination.html.erb
<div class="paging-info row">
  <div class="col-12 col-md-4">
    <div class="page-info">
      <%= page_entries_info view_model.paged_users %>
    </div>
  </div>
  <div class="col-12 col-md-3 d-flex justify-content-lg-end mb-4">
    <%= form_with controller: controller_name, action: action_name, method: "get", class: 'form-inline justify-content-lg-end', local: true do %>
      <div class="">
        <div class="form-group">
          <%= label_tag(:per_page, 'Items per page', class: 'mr-sm-2') %>
          <%= select_tag(:per_page, per_page_options(view_model.per_page),
                         class: "form-control") %>
          <%= hidden_field_tag :page, view_model.page, id: 'page-number' %>
          <%= hidden_field_tag :search, view_model.search %>
          <%= hidden_field_tag :sort, view_model.sort %>
          <%= hidden_field_tag :sort_direction, view_model.sort_direction %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-12 col-md-5">
    <%= paginate view_model.paged_users %>
  </div>
</div>

app/views/users/_search_bar.html.erb
<div class="row search-bar">
  <div class="col mb-2">
    <%= form_with controller: controller_name, action: action_name, method: "get",
      class: 'form-inline', id: "search-bar", local: true do %>
      <div class="form-group mr-4">
        <%= label_tag(:regime, 'Regime', class: 'mr-2') %>
        <%= select_tag(:regime, view_model.regime_options,
                       class: 'form-control') %>
      </div>
      <div class="form-group mr-2">
        <%= label_tag(:role, 'Role', class: 'mr-2') %>
        <%= select_tag(:role, view_model.role_options,
                       class: 'form-control') %>
      </div>
      <div class="input-group col-12 col-lg-3 col-md-3 col-sm-4 mr-2">
        <%= label_tag(:search, 'Search', class: 'sr-only') %>
        <%= search_field_tag(:search, view_model.search,
                             class: 'form-control',
                             placeholder: "Search First or Last Name") %>
        <span class="input-group-btn">
          <%= submit_tag "Search", class: 'btn btn-outline-primary' %>
        </span>
      </div>
      <button class="btn btn-primary"
              type="button"
              id="new-user"
              data-path="<%= new_user_path %>">
        Add User Account
      </button>
      <%= hidden_field_tag :regime, view_model.regime %>
      <%= hidden_field_tag :role, view_model.role %>
      <%= hidden_field_tag :page, view_model.page %>
      <%= hidden_field_tag :sort, view_model.sort %>
      <%= hidden_field_tag :sort_direction, view_model.sort_direction %>
    <% end %>
  </div>
</div>

app/views/users/_table.html.erb
<div class="tcm-table users"
     data-path="<%= users_path %>"
     data-regime="<%= view_model.regime %>"
     data-role="<%= view_model.role %>"
     data-search="<%= view_model.search %>"
     data-page="<%= view_model.page %>"
     data-per-page="<%= view_model.per_page %>"
     data-sort-column="<%= view_model.sort %>"
     data-sort-direction="<%= view_model.sort_direction %>">
     <%= render partial: 'search_bar', locals: { view_model: view_model } %>
<table class="table table-responsive">
  <thead>
    <tr>
      <th><%= sortable :last_name, view_model %></th>
      <th><%= sortable :first_name, view_model %></th>
      <th><%= sortable :email, view_model %></th>
      <th><%= sortable :role, view_model %></th>
      <th><%= t(:regime, scope: 'table.heading.users') %></th>
      <th><%= sortable :enabled, view_model %></th>
      <th>
        <span class='sr-only'>Actions</span>
      </th>
    </tr>
  </thead>
  <tbody>
    <% view_model.paged_users.each do |user| %>
      <tr id="<%= user.id %>" class="<%= user.role %>">
        <td><%= user.last_name %></td>
        <td><%= user.first_name %></td>
        <td><%= user.email %></td>
        <td><%= role_label(user.role) %></td>
        <td><%= regime_names(user) %></td>
        <td><%= user.enabled? ? 'Y' : 'N' %></td>
        <td class="align-middle control-column">
          <%= link_to edit_user_path(user),
            class: "btn btn-sm btn-success" do -%>Edit<span class="sr-only"> user <%= user.full_name %></span>
          <% end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= render partial: "pagination", locals: { view_model: view_model } %>
</div>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-8">
    <h1>Edit User Account</h1>
  </div>
</div>
<%= render 'form', user: @user %>

app/views/users/index.html.erb
<div class="row">
  <div class="col">
    <h1 class="heading">Users</h1>
  </div>
</div>
<div class="users">
  <%= render partial: 'table', locals: { view_model: @view_model } %>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col-8">
    <h1>Add User Account</h1>
  </div>
</div>
<%= render 'form', user: @user %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>