config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, path: "auth", skip: [:registrations]

  as :user do
    get "change_password/edit" => "devise/registrations#edit", as: "edit_user_registration"
    patch "change_password" => "devise/registrations#update", as: "user_registration"
  end

  resources :users do
    get "reinvite", on: :member
  end

  resources :regimes, only: [] do
    resources :permit_categories  # , only: [:index]
    resources :permit_categories_lookup, only: [:index]
    resources :transactions, only: %i[index show edit update] do
      put "approve", on: :collection
      get "audit", on: :member
    end
    resources :history, only: %i[index show]
    resources :retrospectives, only: %i[index show]
    resources :exclusions, only: [:index]
    resources :transaction_files, only: %i[index create]
    resources :imported_transaction_files, only: %i[index show edit update]
    resources :transaction_summary, only: %i[index show]
    resources :retrospective_files, only: [:create]
    resources :retrospective_summary, only: [:index]
    resources :annual_billing_data_files, except: [:destroy]
    resources :exclusion_reasons, except: [:show]
    resources :data_export, only: [:index] do
      get "download", on: :collection
      get "generate", on: :collection
    end
  end

  root to: "transactions#index"

  require "resque/server"
  authenticate(:user, ->(u) { u.admin? }) do
    mount Resque::Server, at: "/jobs"
  end

  match "/404", to: "errors#not_found", via: :all
  match "/422", to: "errors#unprocessable_entity", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
end

app/models/permit_category.rb
# frozen_string_literal: true

class PermitCategory < ApplicationRecord
  include Auditable

  audit_events %i[create update]
  audit_attributes %i[code
                      description
                      valid_from
                      valid_to
                      status]
  belongs_to :regime

  validate :valid_from_is_financial_year
  validate :valid_to_is_financial_year_or_nil
  validate :valid_from_and_valid_to_is_valid_range
  validates :code, format: {
    with: /\A(\d{1,4}|\d{1,4}\.\d{1,4}|\d{1,4}\.\d{1,4}\.\d{1,4})\z/,
    message: "Code must be in dotted numeric format, with 1 to 3 segments between"\
      " 1 and 4 digits long. e.g. 6, 1.2, 9.34.1, 27.111.1234"
  }
  validates :code, presence: true, uniqueness: { scope: %i[regime_id valid_from] }
  validates :description, presence: true, unless: :excluded?
  validates :description, length: { maximum: 150 }
  validate :description_has_no_invalid_characters

  validates :status, inclusion: { in: %w[active excluded],
                                  message: "%{value} is not a valid state" }

  scope :active, -> { where(status: "active") }

  def self.by_financial_year(financial_year)
    t = arel_table
    where(t[:valid_from].lteq(financial_year)).where(t[:valid_to].eq(nil).or(t[:valid_to].gt(financial_year)))
  end

  def self.search(query)
    m = "%#{sanitize_sql_like(query)}%"
    where(arel_table[:code].matches(m).or(arel_table[:description].matches(m)))
  end

  def active?
    status == "active"
  end

  def excluded?
    status == "excluded"
  end

  private

  def valid_from_is_financial_year
    validate_financial_year(:valid_from)
  end

  def valid_to_is_financial_year_or_nil
    validate_financial_year(:valid_to) unless valid_to.nil?
  end

  def validate_financial_year(attr)
    fy = send(attr)
    if fy.blank?
      errors.add(attr, "cannot be blank")
    else
      m = /\A(\d\d)(\d\d)\z/.match(fy)
      err = m.nil?
      err ||= (m[2].to_i != m[1].to_i + 1)
      errors.add(attr, "is not a valid 4 character financial year value") if err
    end
  end

  def valid_from_and_valid_to_is_valid_range
    return if valid_to.nil?

    return unless valid_from >= valid_to

    errors.add(:valid_from, "Valid from must be earlier than valid to")
  end

  def description_has_no_invalid_characters
    return unless description.present?
    return unless description =~ /[?\^£\u2014\u2264\u2265]/

    errors.add(
      :description,
      "^Description contains characters that are not permitted. Please modify your description to remove them."
    )
  end
end

app/controllers/permit_categories_controller.rb
# frozen_string_literal: true

class PermitCategoriesController < AdminController
  include FinancialYear
  include RegimeScope
  before_action :set_regime, only: %i[index new create]
  before_action :set_permit_category, only: %i[show edit update destroy]

  # GET /regime/cfd/permit_categories
  # GET /regime/cfd/permit_categories.json
  def index
    set_regime
    set_financial_year
    q = params.fetch(:search, "")
    sort_col = params.fetch(:sort, :code)
    sort_dir = params.fetch(:sort_direction, "asc")
    pg = params.fetch(:page, 1)
    per_pg = params.fetch(:per_page, 10)
    # As long as the param is set we want to return `true`, else return `false`.
    # We have to pass a default return value to `fetch()` else it will return an
    # error. So the bang at the beginning reverses the `nil?` check at the end
    # which is how we get our true or false result
    #
    # unpaged not set = unpaged.nil? is true  = !true is false
    # unpaged is set  = unpaged.nil? is false = !false is true
    unpaged = !params.fetch(:unpaged, nil).nil?
    @financial_years = Query::PermitCategoryYears.call

    @categories = Query::PermitCategories.call(regime: @regime,
                                               financial_year: @financial_year,
                                               search: q,
                                               sort: sort_col,
                                               sort_direction: sort_dir)

    respond_to do |format|
      format.html do
        @view_model = ViewModels::PermitCategories.new
        @view_model.assign_attributes(
          permit_categories: @categories.page(pg).per(per_pg),
          financial_year: @financial_year,
          search: q,
          sort: sort_col,
          sort_direction: sort_dir,
          page: pg,
          per_page: per_pg,
          financial_years: @financial_years
        )

        if request.xhr?
          render partial: "table", locals: { view_model: @view_model }
        else
          render
        end
      end
      format.json do
        cats = permit_store.search_all(@financial_year, q,
                                       sort_col, sort_dir)
        cats = cats.page(pg).per(per_pg) unless unpaged

        @permit_categories = if unpaged
                               present_categories_unpaged(cats)
                             else
                               present_categories(cats)
                             end

        render json: @permit_categories
      end
    end
  end

  def show; end

  def new
    set_financial_year
    @permit_category = @regime.permit_categories
                              .build(valid_from: @financial_year,
                                     status: "active")
  end

  def edit
    # NOTE: this might not be the actual one we want to edit, it might
    # just the the category that is in use for our given financial year
    # The #update method will have to decide whether to create a new
    # record or modify this one
    set_financial_year
    @permit_category = @regime.permit_categories.find(params[:id])
    @timeline = permit_store.permit_category_versions(@permit_category.code)
  end

  def create
    set_financial_year
    p = permit_category_params
    result = CreatePermitCategory.call(regime: @regime,
                                       valid_from: @financial_year,
                                       user: current_user,
                                       code: p[:code],
                                       description: p[:description])

    @permit_category = result.permit_category

    respond_to do |format|
      if result.success?
        format.html do
          redirect_to regime_permit_categories_path(@regime,
                                                    fy: @financial_year),
                      notice: "Permit category was successfully created."
        end
        format.json { render :show, status: :created, location: regime_permit_category_path(@regime, @permit_category) }
      else
        format.html { render :new }
        format.json { render json: @permit_category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    # NOTE: the submitted record might not be the one we actually want
    # to update
    result = true
    cat = @permit_category

    case params[:commit]
    when "Remove Category"
      if can_remove_permit_category?(cat.code, @financial_year)
        @permit_category = permit_store
                           .update_or_create_new_version(
                             cat.code, permit_category_params[:description],
                             @financial_year, "excluded"
                           )
      else
        @permit_category.errors.add(:base, "^This code is in use and cannot be removed")
      end
    when "Reinstate Category"
      @permit_category = permit_store.update_or_create_new_version(
        cat.code, permit_category_params[:description],
        @financial_year,
        "active"
      )
    else
      @permit_category = permit_store
                         .update_or_create_new_version(
                           cat.code, permit_category_params[:description],
                           @financial_year, cat.status
                         )
    end
    result = @permit_category.errors.empty?

    respond_to do |format|
      if result
        format.html do
          redirect_to(
            regime_permit_categories_path(@regime, fy: @financial_year),
            notice: "Permit category was successfully updated."
          )
        end
        format.json { render :show, status: :ok, location: regime_permit_category_path(@regime, @permit_category) }
      else
        @timeline = permit_store.permit_category_versions(@permit_category.code)
        format.html { render :edit }
        format.json { render json: @permit_category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    # update record status or create new 'excluded' record
    @permit_category.destroy
    respond_to do |format|
      format.html do
        redirect_to regime_permit_categories_url(@regime), notice: "Permit category was successfully destroyed."
      end
      format.json { head :no_content }
    end
  end

  private

  def set_permit_category
    set_regime
    set_financial_year
    @permit_category = @regime.permit_categories.find(params[:id])
  end

  def set_financial_year
    @financial_year = params.fetch(:fy, "1819")
    @financial_year = "1819" unless valid_financial_year? @financial_year
  end

  def permit_category_params
    params.require(:permit_category).permit(:code, :description, :status,
                                            :valid_from, :valid_to)
  end

  def can_remove_permit_category?(code, financial_year)
    # check that no transactions for the given financial year
    # have used this code
    @regime
      .transaction_details
      .financial_year(financial_year)
      .where(category: code)
      .count
      .zero?
  end

  def present_categories_unpaged(categories)
    {
      permit_categories: PermitCategoriesPresenter.wrap(categories)
    }
  end

  def present_categories(categories)
    arr = Kaminari.paginate_array(PermitCategoryPresenter.wrap(categories),
                                  total_count: categories.total_count,
                                  limit: categories.limit_value,
                                  offset: categories.offset_value)
    {
      pagination: {
        current_page: arr.current_page,
        prev_page: arr.prev_page,
        next_page: arr.next_page,
        per_page: arr.limit_value,
        total_pages: arr.total_pages,
        total_count: arr.total_count
      },
      permit_categories: arr
    }
  end

  def permit_store
    @permit_store ||= PermitStorageService.new(@regime, current_user)
  end
end

app/helpers/permit_categories_helper.rb
# frozen_string_literal: true

module PermitCategoriesHelper
  def pretty_financial_year(financial_year)
    "#{financial_year[0..1]}/#{financial_year[2..3]}" unless financial_year.blank?
  end
end

app/views/permit_categories/_form.html.erb
<%= form_with(model: [@regime, permit_category], local: true) do |form| %>
  <h2><%= "Financial Year #{pretty_financial_year @financial_year}"\
    "#{' (Excluded)' if permit_category.excluded?}" -%></h2>
  <%= error_header(permit_category) %>

  <div class="col-lg-6">
    <div class="form-group">
      <%= form.label :code %>
      <% if permit_category.new_record? %>
        <%= form.text_field :code, id: :permit_category_code, class: "form-control" %>
      <div class="panel pt-2 mt-2 pb-2 mb-4 help-text">
        Code must be in dotted number format. It may have between
        1 and 3 segments seperated by a period (.). Each segment
        may be between 1 and 4 digits in length.<br/>
        For example: 27, 9.23, 54.1.1234, 12.34.56
      </div>
      <% else %>
        <%= form.text_field :code, class: "form-control", readonly: true %>
      <% end %>
    </div>

    <div class="form-group">
      <%= form.label :description %>
      <%= form.text_area :description, id: :permit_category_description,
        maxlength: 150, class: "form-control", rows: 4 %>
      <div class="panel pt-2 mt-2 pb-2 mb-4 help-text">
        Description must not be longer than 150 characters and must not
        contain any of the following characters: ?, ^, £, &le;, &ge;,
        &mdash; (long dash).
      </div>
    </div>

      <%= form.hidden_field :status %>
      <%= form.hidden_field :valid_from %>
      <%= form.hidden_field :valid_to %>
      <%= hidden_field_tag :fy, @financial_year %>

      <%= content_for :timeline %>

    <div class="actions">
      <% opts = { data: { turbolinks: false }} %>
      <% if permit_category.new_record? %>
        <%= form.submit opts.merge(class: "btn btn-primary") %>
      <% else %>
        <%= form.submit "Update description",
          opts.merge(class: "btn btn-primary") %>
        <% if permit_category.excluded? %>
          <%= form.submit "Reinstate Category",
            opts.merge(class: "btn btn-warning") %>
        <% else %>
          <%= form.submit "Remove Category", 
            opts.merge(class: "btn btn-danger") %>
        <% end %>
      <% end %>
      <%= link_to 'Cancel',
        regime_permit_categories_path(@regime, fy: @financial_year),
        opts.merge(class: 'btn btn-secondary', role: 'button') %>
    </div>
  </div>
<% end %>

app/views/permit_categories/_pagination.html.erb
<div class="paging-info row">
  <div class="col-12 col-md-4">
    <div class="page-info">
      <%= page_entries_info view_model.permit_categories %>
    </div>
  </div>
  <div class="col-12 col-md-3 d-flex justify-content-lg-end mb-4">
    <%= form_with controller: controller_name, action: action_name, method: "get", class: 'form-inline justify-content-lg-end', local: true do %>
      <div class="">
        <div class="form-group">
          <%= label_tag(:per_page, 'Items per page', class: 'mr-sm-2') %>
          <%= select_tag(:per_page, per_page_options(view_model.per_page),
                         class: "form-control") %>
          <%= hidden_field_tag :page, view_model.page, id: 'page-number' %>
          <%= hidden_field_tag :search, view_model.search %>
          <%= hidden_field_tag :sort, view_model.sort %>
          <%= hidden_field_tag :sort_direction, view_model.sort_direction %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-12 col-md-5">
    <%= paginate view_model.permit_categories %>
  </div>
</div>

app/views/permit_categories/_search_bar.html.erb
<div class="row search-bar">
  <div class="col mb-2">
    <%= form_with controller: controller_name, action: action_name, method: "get",
      class: 'form-inline', id: "search-bar", local: true do %>
      <div class="form-group mr-2">
        <%= label_tag(:fy, 'FY', class: 'mr-2') %>
        <%= select_tag(:fy, permit_financial_year_options(view_model.financial_years,
                                                          view_model.financial_year),
                       class: 'form-control') %>
      </div>
      <div class="input-group col-12 col-lg-3 col-md-3 col-sm-4 mr-2">
        <%= label_tag(:search, 'Search', class: 'sr-only') %>
        <%= search_field_tag(:search, view_model.search,
                             class: 'form-control',
                             placeholder: "Search Code or Description") %>
        <span class="input-group-btn">
          <%= submit_tag "Search", class: 'btn btn-outline-primary' %>
        </span>
      </div>
      <button class="btn btn-primary"
              type="button"
              id="new-category"
              data-path="<%= new_regime_permit_category_path(@regime) %>">
        New Permit Category
      </button>
      <%= hidden_field_tag :financial_year, view_model.financial_year %>
      <%= hidden_field_tag :page, view_model.page %>
      <%= hidden_field_tag :sort, view_model.sort %>
      <%= hidden_field_tag :sort_direction, view_model.sort_direction %>
    <% end %>
  </div>
</div>

app/views/permit_categories/_table.html.erb
<div class="tcm-table permit-categories"
     data-path="<%= regime_permit_categories_path(@regime) %>"
     data-financial-year="<%= view_model.financial_year %>"
     data-search="<%= view_model.search %>"
     data-page="<%= view_model.page %>"
     data-per-page="<%= view_model.per_page %>"
     data-sort-column="<%= view_model.sort %>"
     data-sort-direction="<%= view_model.sort_direction %>">
     <%= render partial: 'search_bar', locals: { view_model: view_model } %>
<table class="table table-responsive">
  <thead>
    <tr>
      <th><%= sortable :code, view_model %></th>
      <th><%= sortable :description, view_model %></th>
      <th>
        <span class='sr-only'>Actions</span>
      </th>
    </tr>
  </thead>
  <tbody>
    <% view_model.permit_categories.each do |category| %>
      <tr id="<%= category.id %>" class="<%= category.status %>">
        <td><%= category.code %></td>
        <td><%= category.description %></td>
        <td class="align-middle control-column">
          <%= link_to edit_regime_permit_category_path(@regime, category, fy: @financial_year),
            class: "btn btn-sm btn-success" do -%>Edit<span class="sr-only"> permit category with code <%= category.code %></span>
          <% end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= render partial: "pagination", locals: { view_model: view_model } %>
</div>

app/views/permit_categories/edit.html.erb
<div class="row">
  <div class="col">
    <h1 class="heading">Edit Permit Category</h1>
  </div>
</div>
<% content_for :timeline do %>
  <div class="row timeline">
    <div class="col">
      <h3>Timeline</h3>
      <table class="table table-sm">
        <thead>
          <tr>
            <th>Year</th>
            <th>Description</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          <% @timeline.each do |pc| %>
            <tr class="#{'excluded' if pc.excluded? }">
              <td><%= pretty_financial_year(pc.valid_from) %></td>
              <td><%= pc.description %></td>
              <td><%= pc.status.capitalize %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% end %>
<%= render 'form', permit_category: @permit_category %>

app/views/permit_categories/index.html.erb
<%# <% content_for :head do %>
<%#   <%= javascript_pack_tag 'transactions' %>
<%#   <%= stylesheet_pack_tag 'transactions' %>
<%# <% end %>
<div class="row">
  <div class="col">
    <h1 class="heading">Permit Categories</h1>
  </div>
</div>
<div class="categories">
  <%= render partial: 'table', locals: { view_model: @view_model } %>
</div>

app/views/permit_categories/new.html.erb
<div class="row">
  <div class="col-8">
    <h1>New Permit Category</h1>
  </div>
</div>
<%= render 'form', permit_category: @permit_category %>