config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, path: "auth", skip: [:registrations]

  as :user do
    get "change_password/edit" => "devise/registrations#edit", as: "edit_user_registration"
    patch "change_password" => "devise/registrations#update", as: "user_registration"
  end

  resources :users do
    get "reinvite", on: :member
  end

  resources :regimes, only: [] do
    resources :permit_categories  # , only: [:index]
    resources :permit_categories_lookup, only: [:index]
    resources :transactions, only: %i[index show edit update] do
      put "approve", on: :collection
      get "audit", on: :member
    end
    resources :history, only: %i[index show]
    resources :retrospectives, only: %i[index show]
    resources :exclusions, only: [:index]
    resources :transaction_files, only: %i[index create]
    resources :imported_transaction_files, only: %i[index show edit update]
    resources :transaction_summary, only: %i[index show]
    resources :retrospective_files, only: [:create]
    resources :retrospective_summary, only: [:index]
    resources :annual_billing_data_files, except: [:destroy]
    resources :exclusion_reasons, except: [:show]
    resources :data_export, only: [:index] do
      get "download", on: :collection
      get "generate", on: :collection
    end
  end

  root to: "transactions#index"

  require "resque/server"
  authenticate(:user, ->(u) { u.admin? }) do
    mount Resque::Server, at: "/jobs"
  end

  match "/404", to: "errors#not_found", via: :all
  match "/422", to: "errors#unprocessable_entity", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
end

app/models/annual_billing_data_file.rb
# frozen_string_literal: true

class AnnualBillingDataFile < ApplicationRecord
  belongs_to :regime, inverse_of: :annual_billing_data_files
  has_many :data_upload_errors, inverse_of: :annual_billing_data_file, dependent: :destroy

  validates :filename, presence: true
  validates :number_of_records, numericality: { only_integer: true }
  validates :status, inclusion: { in: %w[new uploaded processing completed failed] }

  def file_types
    AnnualBillingDataFileFormat::FILE_TYPES
  end

  def log_error(line, msg)
    data_upload_errors.create(line_number: line, message: msg)
  end

  def state
    Bstard.define do |fsm|
      fsm.initial status
      fsm.event :upload, new: :uploaded
      fsm.event :process, uploaded: :processing
      fsm.event :complete, processing: :completed
      fsm.event :error, processing: :failed, new: :failed
      fsm.when :any do |_event, _prev_state, new_state|
        update_attribute(:status, new_state)
      end
    end
  end

  def finished_processing?
    s = state
    s.completed? || s.failed?
  end
end

app/controllers/annual_billing_data_files_controller.rb
# frozen_string_literal: true

class AnnualBillingDataFilesController < ApplicationController
  include ViewModelBuilder
  include RegimeScope

  before_action :set_regime, only: %i[index new create]
  before_action :set_upload, only: %i[show edit update]

  # GET /regimes/:regime_id/transactions
  # GET /regimes/:regime_id/transactions.json
  def index
    # list of uploads
    @uploads = @regime.annual_billing_data_files.order(created_at: :desc)
  end

  # GET /regimes/:regime_id/transactions/1
  # GET /regimes/:regime_id/transactions/1.json
  def show
    @view_model = build_annual_billing_view_model

    respond_to do |format|
      format.html do
        if request.xhr?
          render partial: "table", locals: { view_model: @view_model }
        else
          render
        end
      end
    end
  end

  # GET /regimes/:regimes_id/transactions/1/edit
  def edit
    # possible re-run matching and merging process?
  end

  # PATCH/PUT /regimes/:regimes_id/transactions/1
  # PATCH/PUT /regimes/:regimes_id/transactions/1.json
  def update
    # possible re-run matching and merging process?
  end

  def new
    @upload = data_service.new_upload
  end

  def create
    @upload = data_service.upload(file_params)

    if @upload.errors.empty? && @upload.save
      # start background job
      AnnualBillingDataImportJob.perform_later(current_user.id, @upload.id)
      # the show page will display progress while importing
      redirect_to regime_annual_billing_data_file_path(@regime, @upload)
    else
      render "new"
    end
  end

  private

  def set_upload
    set_regime
    @upload = data_service.find(params[:id])
  end

  def file_params
    params.require(:annual_billing_data_file).permit(:data_file)
  end

  def present_errors(errors)
    error_data = errors.map do |e|
      {
        id: e.id,
        line_number: e.line_number,
        message: e.message
      }
    end
    {
      errors: error_data,
      pagination: {
        current_page: errors.current_page,
        prev_page: errors.prev_page,
        next_page: errors.next_page,
        per_page: errors.limit_value,
        total_pages: errors.total_pages,
        total_count: errors.total_count
      }
    }
  end

  def present_file(upload, errors)
    {
      filename: File.basename(upload.filename),
      upload_date: helpers.formatted_date(upload.created_at, include_time: true),
      status: upload.status.humanize,
      success_count: upload.success_count,
      failed_count: upload.failed_count,
      error_list: present_errors(errors)
    }
  end

  def data_service
    @data_service ||= AnnualBillingDataFileService.new(@regime, current_user)
  end
end

app/views/annual_billing_data_files/_csv_help.html.erb
<details>
  <summary role="button" aria-controls="csv-file-help">
    <span class="summary">Help with the <strong><%= regime.title %></strong> CSV file format</span>
  </summary>
  <div class="panel" id="csv-file-help">
    <p class="col-lg-8"><em>CSV</em> stands for <em>'Comma Separated Values'</em>.
    A CSV formatted file contains one record per-row with
    each field in the record delimited by a comma (',').
    Each row in the file should contain the following fields:</p>

    <%= annual_billing_csv_column_descriptions_for(regime) %>
  </div>
</details>

app/views/annual_billing_data_files/_form.html.erb
<%= form_with(model: [@regime, upload], local: true, html: { multipart: true } ) do |form| %>
  <%= error_header(upload) %>

  <div class="col-lg-6">
    <div class="form-group">
      <%= form.file_field :data_file,
          accept: upload.file_types,
          aria: { labelledby: 'annual-billing-data-upload' } %>
      <%= form.hidden_field :id %>
    </div>

    <div class="actions">
      <%= form.submit class: "btn btn-primary" %>
      <%= link_to 'Back', regime_permit_categories_path(@regime),
        class: "btn btn-secondary", role: "button" %>
    </div>
  </div>
<% end %>

app/views/annual_billing_data_files/_table.html.erb
<div class="tcm-table"
     data-path="<%= regime_annual_billing_data_file_path(view_model.regime,
                                                         view_model.upload) %>"
     data-sort-column="<%= view_model.sort %>"
     data-sort-direction="<%= view_model.sort_direction %>"
     data-page="<%= view_model.page %>"
     data-per-page="<%= view_model.per_page %>" >
  <table class="table table-responsive upload-errors">
    <thead>
      <tr>
        <th><%= sortable :line_number, view_model %></th>
        <th><%= sortable :message, view_model %></th>
      </tr>
    </thead>
    <tbody>
      <% view_model.errors.each do |error| %>
        <tr id="<%= error.id %>">
          <td><%= error.line_number %></td>
          <td><%= error.message %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= render partial: "shared/pagination", locals: { collection: view_model.errors,
    include_export: false } %>
</div>

app/views/annual_billing_data_files/_upload_details.html.erb
<dl class="row" id="upload-details">
  <dt class="col-sm-4 col-md-3">Filename</dt>
  <dd class="col-sm-7 col-md-8"><%= File.basename @upload.filename %></dd>
  <dt class="col-sm-4 col-md-3">Date uploaded</dt>
  <dd class="col-sm-7 col-md-8"><%= formatted_date(@upload.created_at, include_time: true) %></dd>
  <dt class="col-sm-4 col-md-3">Status</dt>
  <dd class="col-sm-7 col-md-8" id="upload-status"><%= @upload.status.humanize %></dd>
  <dt class="col-sm-4 col-md-3">Records updated</dt>
  <dd class="col-sm-7 col-md-8"><%= @upload.success_count %></dd>
  <dt class="col-sm-4 col-md-3">Errors detected</dt>
  <dd class="col-sm-7 col-md-8"><%= @upload.failed_count %></dd>
</dl>

app/views/annual_billing_data_files/index.html.erb
<div class="row mb-4">
  <div class="col">
    <h1 id="annual-billing-data-heading">Annual Billing Data Files</h1>
  </div>
</div>
<div class="row mb-4">
  <div class="col">
    <%= link_to 'Upload Annual Billing Data',
      new_regime_annual_billing_data_file_path(@regime),
      class: 'btn btn-primary', role: 'button' %>
  </div>
</div>
<div class="row">
  <div class="col">
    <table class="table table-responsive">
      <thead>
        <tr>
          <th>Filename</th>
          <th>Date Uploaded</th>
          <th>Status</th>
          <th>Errors</th>
        </tr>
      </thead>
      <tbody>
        <% @uploads.each do |upload| %>
          <tr>
            <td>
              <%= link_to File.basename(upload.filename),
                regime_annual_billing_data_file_path(@regime, upload) %>
            </td>
            <td><%= formatted_date(upload.created_at, include_time: true) %></td>
            <td><%= upload.status.humanize %></td>
            <td><%= upload.failed_count %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/annual_billing_data_files/new.html.erb
<div class="row mb-4">
  <div class="col">
    <h1 id="annual-billing-data-heading">Upload Annual Billing Data</h1>
  </div>
</div>

<%= form_with(model: [@regime, @upload], local: true,
              class: "annual-billing-upload",
              html: { multipart: true } ) do |form| %>
  <%= error_header(@upload, title: "Unable to proceed") %>
  <div class="row">
    <div class="col">
      <p>Select the annual billing data file to upload (<strong>CSV</strong> format).</p>
      <%= render partial: 'csv_help', locals: { regime: @regime } %>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-6">
      <div class="form-group">
        <%= form.file_field :data_file,
          accept: @upload.file_types,
          aria: { labelledby: 'annual-billing-data-heading' } %>
        <%= form.hidden_field :id %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-6 actions">
      <%= form.submit 'Upload and Import Data',  class: "btn btn-primary" %>
      <%= link_to 'Cancel', regime_annual_billing_data_files_path(@regime),
        class: "btn btn-secondary", role: "button" %>
    </div>
  </div>
<% end %>

app/views/annual_billing_data_files/show.html.erb
<div class="row mb-4">
  <div class="col">
    <h1 id="annual-billing-data-heading">Annual Billing Data File Details</h1>
  </div>
</div>
<div class="panel">
  <dl class="row">
    <dt class="col-sm-4 col-md-3">Filename</dt>
    <dd class="col-sm-7 col-md-8"><%= File.basename @view_model.upload.filename %></dd>
    <dt class="col-sm-4 col-md-3">Date uploaded</dt>
    <dd class="col-sm-7 col-md-8"><%= formatted_date(@view_model.upload.created_at, include_time: true) %></dd>
    <dt class="col-sm-4 col-md-3">Status</dt>
    <dd class="col-sm-7 col-md-8"><%= @view_model.upload.status.humanize %></dd>
    <dt class="col-sm-4 col-md-3">Records updated</dt>
    <dd class="col-sm-7 col-md-8"><%= @view_model.upload.success_count %></dd>
    <dt class="col-sm-4 col-md-3">Errors detected</dt>
    <dd class="col-sm-7 col-md-8"><%= @view_model.upload.failed_count %></dd>
  </dl>
</div>
<% if @view_model.upload.failed_count.positive? %>
  <div>
    <div class="row mt-2">
      <div class="col">
        <h2>Errors</h2>
      </div>
    </div>
    <%= render partial: "table", locals: { view_model: @view_model } %>
  </div>
<% end %>
<div class="row">
  <div class="col-lg-6 actions">
    <%= link_to 'Back', regime_annual_billing_data_files_path(@view_model.regime),
      class: "btn btn-secondary", role: "button" %>
  </div>
</div>