config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, path: "auth", skip: [:registrations]

  as :user do
    get "change_password/edit" => "devise/registrations#edit", as: "edit_user_registration"
    patch "change_password" => "devise/registrations#update", as: "user_registration"
  end

  resources :users do
    get "reinvite", on: :member
  end

  resources :regimes, only: [] do
    resources :permit_categories  # , only: [:index]
    resources :permit_categories_lookup, only: [:index]
    resources :transactions, only: %i[index show edit update] do
      put "approve", on: :collection
      get "audit", on: :member
    end
    resources :history, only: %i[index show]
    resources :retrospectives, only: %i[index show]
    resources :exclusions, only: [:index]
    resources :transaction_files, only: %i[index create]
    resources :imported_transaction_files, only: %i[index show edit update]
    resources :transaction_summary, only: %i[index show]
    resources :retrospective_files, only: [:create]
    resources :retrospective_summary, only: [:index]
    resources :annual_billing_data_files, except: [:destroy]
    resources :exclusion_reasons, except: [:show]
    resources :data_export, only: [:index] do
      get "download", on: :collection
      get "generate", on: :collection
    end
  end

  root to: "transactions#index"

  require "resque/server"
  authenticate(:user, ->(u) { u.admin? }) do
    mount Resque::Server, at: "/jobs"
  end

  match "/404", to: "errors#not_found", via: :all
  match "/422", to: "errors#unprocessable_entity", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
end

app/models/view_models/retrospectives.rb
# frozen_string_literal: true

module ViewModels
  class Retrospectives < Transactions
    def initialize(params = {})
      super(params)
      @permit_all_regions = true
    end

    def fetch_transactions
      Query::PreSrocTransactions.call(regime: regime,
                                      region: region,
                                      sort: sort,
                                      sort_direction: sort_direction,
                                      financial_year: financial_year,
                                      search: search)
    end

    def region_options
      all_region_options
    end
  end
end

app/controllers/retrospectives_controller.rb
# frozen_string_literal: true

class RetrospectivesController < ApplicationController
  include ViewModelBuilder
  include QueryTransactions
  include CsvExporter
  include RegimeScope

  before_action :set_regime, only: [:index]
  before_action :set_transaction, only: [:show]
  before_action :redirect_if_waste

  # GET /regimes/:regime_id/history
  # GET /regimes/:regime_id/history.json
  def index
    @view_model = build_retrospectives_view_model

    respond_to do |format|
      format.html do
        render partial: "table", locals: { view_model: @view_model } if request.xhr?
      end
      format.csv do
        export_data_user_check!
        result = BatchCsvExport.call(regime: @regime,
                                     query: @view_model.fetch_transactions)
        if result.success?
          set_streaming_headers
          self.response_body = result.csv_stream
        end
      end
    end
  end

  # GET /regimes/:regime_id/history/1
  # GET /regimes/:regime_id/history/1.json
  def show; end

  private

  def redirect_if_waste
    redirect_to regime_transactions_path(@regime) if @regime.waste?
  end

  def present_transactions(transactions)
    Kaminari.paginate_array(presenter.wrap(transactions, current_user),
                            total_count: transactions.total_count,
                            limit: transactions.limit_value,
                            offset: transactions.offset_value)
  end

  def present_transactions_for_json(transactions, selected_region, regions)
    arr = present_transactions(transactions)
    {
      pagination: {
        current_page: arr.current_page,
        prev_page: arr.prev_page,
        next_page: arr.next_page,
        per_page: arr.limit_value,
        total_pages: arr.total_pages,
        total_count: arr.total_count
      },
      transactions: arr,
      selected_region: selected_region,
      regions: region_options(regions)
    }
  end

  def region_options(regions)
    regions.map { |r| { label: r, value: r } }
  end

  def financial_year_options(fy_list)
    fys = fy_list.map { |fy| { label: "#{fy[0..1]}/#{fy[2..3]}", value: fy } }
    fys = [{ label: "All", value: "" }] + fys if fys.count > 1
    fys
  end
end

app/views/retrospectives/_cfd_table.html.erb
<table class="table table-responsive">
  <thead>
    <tr>
      <th><span class='sr-only'>Details</span></th>
      <th><%= sortable :file_reference, view_model %></th>
      <th><%= sortable :file_date, view_model %></th>
      <th><%= sortable :customer_reference, view_model %></th>
      <th><%= sortable :consent_reference, view_model %></th>
      <th><%= sortable :version, view_model %></th>
      <th><%= sortable :discharge, view_model %></th>
      <th><%= sortable :variation, view_model %></th>
      <th><%= sortable :period, view_model %></th>
      <th class="text-right"><%= sortable :line_amount, view_model %></th>
    </tr>
  </thead>
  <tbody>
    <% view_model.present_paged_transactions.each do |transaction| %>
      <%= render partial: 'cfd_transaction', locals: { transaction: transaction,
      data_path: regime_transaction_path(view_model.regime, transaction) } %>
    <% end %>
  </tbody>
</table>

app/views/retrospectives/_cfd_transaction.html.erb
<tr id=<%= transaction.id %>>
  <td class="align-middle details-button-column">
    <button class="btn btn-sm show-details-button"
            data-path="<%= data_path %>">
            <span class='sr-only'>Show details for Consent <%= transaction.consent_reference %></span>
            <span class="aria-hidden oi oi-magnifying-glass"></span>
    </button>
  </td>
  <td class="align-middle">
    <%= transaction.original_filename %>
  </td>
  <td class="align-middle">
    <%= transaction.original_file_date_table %>
  </td>
  <td class="align-middle">
    <%= transaction.customer_reference %>
  </td>
  <td class="align-middle">
    <%= transaction.consent_reference %>
  </td>
  <td class="align-middle">
    <%= transaction.version %>
  </td>
  <td class="align-middle">
    <%= transaction.discharge_reference %>
  </td>
  <td class="align-middle">
    <%= transaction.clean_variation_percentage %>
  </td>
  <td class="align-middle">
    <%= transaction.period %>
  </td>
  <td class="align-middle text-right">
    <%= transaction.currency_line_amount %>
  </td>
</tr>

app/views/retrospectives/_pas_table.html.erb
<table class="table table-responsive">
  <thead>
    <tr>
      <th><span class='sr-only'>Details</span></th>
      <th><%= sortable :file_reference, view_model %></th>
      <th><%= sortable :file_date, view_model %></th>
      <th><%= sortable :customer_reference, view_model %></th>
      <th><%= sortable :permit_reference, view_model %></th>
      <th><%= sortable :original_permit_reference, view_model %></th>
      <th><%= sortable :compliance_band, view_model %></th>
      <th><%= sortable :period, view_model %></th>
      <th class="text-right"><%= sortable :line_amount, view_model %></th>
    </tr>
  </thead>
  <tbody>
    <% view_model.present_paged_transactions.each do |transaction| %>
      <%= render partial: 'pas_transaction', locals: { transaction: transaction ,
      data_path: regime_transaction_path(view_model.regime, transaction) } %>
    <% end %>
  </tbody>
</table>

app/views/retrospectives/_pas_transaction.html.erb
<tr id=<%= transaction.id %>>
  <td class="align-middle details-button-column">
    <button class="btn btn-sm show-details-button"
            data-path="<%= data_path %>">
            <span class='sr-only'>Show details for Permit <%= transaction.permit_reference %></span>
            <span class="aria-hidden oi oi-magnifying-glass"></span>
    </button>
  </td>
  <td class="align-middle">
    <%= transaction.original_filename %>
  </td>
  <td class="align-middle">
    <%= transaction.original_file_date_table %>
  </td>
  <td class="align-middle">
    <%= transaction.customer_reference %>
  </td>
  <td class="align-middle">
    <%= transaction.permit_reference %>
  </td>
  <td class="align-middle">
    <%= transaction.original_permit_reference %>
  </td>
  <td class="align-middle">
    <%= transaction.compliance_band %>
  </td>
  <td class="align-middle">
    <%= transaction.period %>
  </td>
  <td class="align-middle text-right">
    <%= transaction.currency_line_amount %>
  </td>
</tr>

app/views/retrospectives/_search_bar.html.erb
<div class="row">
  <div class="col mb-2">
    <%= form_with controller: controller_name, action: action_name, method: "get",
      class: 'form-inline', id: 'search-bar', local: true do %>
      <div class="form-group mr-4">
        <%= label_tag(:mode, 'View', class: 'mr-2') %>
        <%= select_tag(:mode, view_options(view_mode), class: 'form-control') %>
      </div>
      <div class="form-group mr-4">
        <%= label_tag(:region, 'Region', class: 'mr-2') %>
        <%= select_tag(:region, view_model.region_options,
                       class: 'form-control') %>
      </div>
      <div class="form-group mr-4">
        <%= label_tag(:fy, 'FY', class: 'mr-2') %>
        <%= select_tag(:fy, view_model.financial_year_options,
                       class: 'form-control') %>
      </div>
      <div class="input-group col-12 col-md-5 mr-2">
        <%= label_tag(:search, 'Search', class: 'sr-only') %>
        <%= search_field_tag(:search, view_model.search,
                             class: 'form-control',
                             placeholder: search_placeholder(@regime)) %>
        <span class="input-group-btn">
          <%= submit_tag "Search", class: 'btn btn-outline-primary' %>
        </span>
      </div>
      <% unless current_user.can_read_only? %>
        <button class="btn btn-primary mr-4 generate-transaction-file-btn">Generate Pre-SRoC File</button>
      <% end %>
      <%= hidden_field_tag :page, 1 %>
      <%= hidden_field_tag :sort, params[:sort] %>
      <%= hidden_field_tag :sort_direction, params[:sort_direction] %>
    <% end %>
  </div>
</div>

app/views/retrospectives/_table.html.erb
<div class="tcm-table"
     data-path="<%= regime_retrospectives_path(view_model.regime) %>"
     data-summary-path="<%= regime_retrospective_summary_index_path(view_model.regime) %>"
     data-region="<%= view_model.region %>"
     data-financial-year="<%= view_model.financial_year %>"
     data-search="<%= view_model.search %>"
     data-page="<%= view_model.page %>"
     data-per-page="<%= view_model.per_page %>"
     data-sort-column="<%= view_model.sort %>"
     data-sort-direction="<%= view_model.sort_direction %>">
     <%= render partial: 'search_bar', locals: { view_model: view_model,
                                                 view_mode: 'retrospective' } %>
     <%= render partial: view_model.table_partial_name, locals: { view_model: view_model } %>
     <%= render partial: "shared/pagination", locals: { collection: view_model.present_paged_transactions, include_export: current_user.can_export_data? } %>
  <div id="summary-dialog"
       data-summary-path="<%= regime_retrospective_summary_index_path(view_model.regime) %>">
  </div>
  <%= render partial: "shared/data_protection_dialog" %>
</div>

app/views/retrospectives/_wml_table.html.erb
<table class="table table-responsive">
  <thead>
    <tr>
      <th><%= sortable :file_reference, view_model %></th>
      <th><%= sortable :file_date, view_model %></th>
      <th><%= sortable :customer_reference, view_model %></th>
      <th><%= sortable :permit_reference, view_model %></th>
      <th><%= sortable :compliance_band, view_model %></th>
      <th><%= sortable :period, view_model %></th>
      <th class="text-right"><%= sortable :amount, view_model %></th>
      <th><span class='sr-only'>Actions</span></th>
    </tr>
  </thead>
  <tbody>
    <% view_model.present_paged_transactions.each do |transaction| %>
      <%= render partial: 'wml_transaction', locals: { transaction: transaction,
      data_path: regime_transaction_path(view_model.regime, transaction) } %>
    <% end %>
  </tbody>
</table>

app/views/retrospectives/_wml_transaction.html.erb
<tr id=<%= transaction.id %>>
  <td class="align-middle details-button-column">
    <button class="btn btn-sm show-details-button"
            data-path="<%= data_path %>">
            <span class='sr-only'>Show details for Permit <%= transaction.permit_reference %></span>
            <span class="aria-hidden oi oi-magnifying-glass"></span>
    </button>
  </td>
  <td class="align-middle">
    <%= transaction.original_filename %>
  </td>
  <td class="align-middle">
    <%= transaction.original_file_date_table %>
  </td>
  <td class="align-middle">
    <%= transaction.customer_reference %>
  </td>
  <td class="align-middle">
    <%= transaction.permit_reference %>
  </td>
  <td class="align-middle">
    <%= transaction.compliance_band %>
  </td>
  <td class="align-middle">
    <%= transaction.period %>
  </td>
  <td class="align-middle text-right">
    <%= transaction.currency_line_amount %>
  </td>
</tr>

app/views/retrospectives/index.html.erb
<div class="retrospective">
  <div class="row mb-4">
    <div class="col">
      <h1 id="view-title"><%= t('.title') %></h1>
    </div>
  </div>
  <%= render partial: "table", locals: { view_model: @view_model } %>
</div>